services:
  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: "bridge"
    restart: always
    ports:
      - "8000:8000"